---
- hosts: localhost
  become: yes
  vars:
    ldap_domain: "example.com"
    ldap_org: "ExampleOrg"
    ldap_admin_pass: "adminpass"

  tasks:
    - name: Настроить slapd debconf перед установкой
      debconf:
        name: slapd
        question: "{{ item.q }}"
        value: "{{ item.v }}"
        vtype: "{{ item.t }}"
      loop:
        - { q: "slapd/internal/adminpw", v: "{{ ldap_admin_pass }}", t: "password" }
        - { q: "slapd/internal/generated_adminpw", v: "{{ ldap_admin_pass }}", t: "password" }
        - { q: "slapd/password1", v: "{{ ldap_admin_pass }}", t: "password" }
        - { q: "slapd/password2", v: "{{ ldap_admin_pass }}", t: "password" }
        - { q: "slapd/domain", v: "{{ ldap_domain }}", t: "string" }
        - { q: "slapd/organization", v: "{{ ldap_org }}", t: "string" }
        - { q: "slapd/backend", v: "MDB", t: "select" }
        - { q: "slapd/purge_database", v: "true", t: "boolean" }
        - { q: "slapd/move_old_database", v: "true", t: "boolean" }

    - name: Установить OpenLDAP и утилиты
      apt:
        name:
          - slapd
          - ldap-utils
        state: present
        update_cache: yes

    - name: Создать структуру пользователей и групп (LDIF)
      copy:
        dest: /tmp/base.ldif
        content: |
          dn: ou=People,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: organizationalUnit
          ou: People

          dn: ou=Groups,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: organizationalUnit
          ou: Groups

          dn: uid=user1,ou=People,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: inetOrgPerson
          cn: User One
          sn: One
          uid: user1
          userPassword: pass1

          dn: uid=user2,ou=People,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: inetOrgPerson
          cn: User Two
          sn: Two
          uid: user2
          userPassword: pass2

          dn: cn=group1,ou=Groups,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: posixGroup
          cn: group1
          gidNumber: 5000

          dn: cn=group2,ou=Groups,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
          objectClass: posixGroup
          cn: group2
          gidNumber: 5001

    - name: Добавить базовые записи в LDAP
      command: >
        ldapadd -x
        -D "cn=admin,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}"
        -w {{ ldap_admin_pass }}
        -f /tmp/base.ldif
