---
- hosts: localhost
  become: yes
  collections:
    - community.general

  vars:
    ldap_domain: "example.com"
    ldap_admin: "cn=admin,dc=example,dc=com"
    ldap_admin_pass: "adminpass"

  tasks:
    - name: Установить OpenLDAP и модули
      apt:
        name: [slapd, ldap-utils, python3-ldap]
        state: present
        update_cache: yes

    - name: Создать People OU
      community.general.ldap_entry:
        dn: "ou=People,dc=example,dc=com"
        objectClass: organizationalUnit
        attributes:
          ou: People
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"

    - name: Создать Groups OU
      community.general.ldap_entry:
        dn: "ou=Groups,dc=example,dc=com"
        objectClass: organizationalUnit
        attributes:
          ou: Groups
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"

    - name: Создать user1
      community.general.ldap_entry:
        dn: "uid=user1,ou=People,dc=example,dc=com"
        objectClass: inetOrgPerson
        attributes:
          cn: "User One"
          sn: "One"
          uid: "user1"
          userPassword: "pass1"
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"

    - name: Создать user2
      community.general.ldap_entry:
        dn: "uid=user2,ou=People,dc=example,dc=com"
        objectClass: inetOrgPerson
        attributes:
          cn: "User Two"
          sn: "Two"
          uid: "user2"
          userPassword: "pass2"
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"

    - name: Создать group1
      community.general.ldap_entry:
        dn: "cn=group1,ou=Groups,dc=example,dc=com"
        objectClass: posixGroup
        attributes:
          cn: "group1"
          gidNumber: "5000"
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"

    - name: Создать group2
      community.general.ldap_entry:
        dn: "cn=group2,ou=Groups,dc=example,dc=com"
        objectClass: posixGroup
        attributes:
          cn: "group2"
          gidNumber: "5001"
        bind_dn: "{{ ldap_admin }}"
        bind_pw: "{{ ldap_admin_pass }}"
        server_uri: "ldap://localhost"
